# Generated by Django 3.2.6 on 2021-09-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='secondary_abilty',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
